server:
  port: 8090

spring:
  datasource:
    # 订单数据源
    order:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/orders?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: root
      password: root

    # 商品数据源
    goods:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/goods?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: root
      password: root
